import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navigation = [
    { name: "Home", href: "/" },
    { name: "About Us", href: "/about" },
    { name: "Our Services", href: "/services" },
    { name: "Khutba Series", href: "/khutba-Series" },
    { name: "Directions", href: "/directions" },
    { name: "Contact Us", href: "/contact" },
    { name: "Resources & Links", href: "/resources" },
  ];
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white">
          <nav
            className="mx-auto flex max-w-7xl items-center justify-between p-4 lg:p-6"
            aria-label="Global"
          >
            {/* Desktop Navigation */}
            <div className="hidden lg:flex lg:gap-x-12">
              {navigation.map((item) => (
                <Link key={item.name} href={item.href}>
                  <div className="text-sm font-semibold leading-6 text-gray-900">
                    {item.name}
                  </div>
                </Link>
              ))}
            </div>
            {/* Mobile Navigation (Hamburger Menu Placeholder) */}
            <div className="lg:hidden">
              {/* Add your hamburger menu here */}
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
